export const categories = [
  { id: '1', name: 'Hamburguesas', icon: '🍔', color: '#FF6B6B' },
  { id: '2', name: 'Pizza', icon: '🍕', color: '#4ECDC4' },
  { id: '3', name: 'Ensaladas', icon: '🥗', color: '#95E1D3' },
  { id: '4', name: 'Bebidas', icon: '🥤', color: '#F38181' },
  { id: '5', name: 'Postres', icon: '🍰', color: '#AA96DA' },
  { id: '6', name: 'Pastas', icon: '🍝', color: '#FCBAD3' },
  { id: '7', name: 'Pollo', icon: '🍗', color: '#FFD93D' },
  { id: '8', name: 'Sushi', icon: '🍣', color: '#6BCB77' },
];

export const products = [
  {
    id: '1',
    name: 'Hamburguesa Clásica',
    description: 'Carne de res, lechuga, tomate, cebolla y salsas especiales',
    price: 25000,
    image: '🍔',
    category: '1',
    rating: 4.5,
    preparationTime: '20-30 min',
  },
  {
    id: '2',
    name: 'Hamburguesa BBQ',
    description: 'Carne de res con salsa BBQ, tocino, queso cheddar y aros de cebolla',
    price: 30000,
    image: '🍔',
    category: '1',
    rating: 4.8,
    preparationTime: '25-35 min',
  },
  {
    id: '3',
    name: 'Pizza Margarita',
    description: 'Salsa de tomate, mozzarella fresca y albahaca',
    price: 35000,
    image: '🍕',
    category: '2',
    rating: 4.6,
    preparationTime: '30-40 min',
  },
  {
    id: '4',
    name: 'Pizza Pepperoni',
    description: 'Salsa de tomate, mozzarella y pepperoni',
    price: 38000,
    image: '🍕',
    category: '2',
    rating: 4.7,
    preparationTime: '30-40 min',
  },
  {
    id: '5',
    name: 'Ensalada César',
    description: 'Lechuga romana, pollo a la parrilla, crutones, parmesano y aderezo césar',
    price: 22000,
    image: '🥗',
    category: '3',
    rating: 4.3,
    preparationTime: '15-20 min',
  },
  {
    id: '6',
    name: 'Ensalada Griega',
    description: 'Lechuga, tomate, pepino, cebolla, aceitunas y queso feta',
    price: 20000,
    image: '🥗',
    category: '3',
    rating: 4.4,
    preparationTime: '15-20 min',
  },
  {
    id: '7',
    name: 'Coca Cola',
    description: 'Refresco 500ml',
    price: 5000,
    image: '🥤',
    category: '4',
    rating: 4.9,
    preparationTime: '5 min',
  },
  {
    id: '8',
    name: 'Limonada Natural',
    description: 'Limonada fresca natural 500ml',
    price: 8000,
    image: '🥤',
    category: '4',
    rating: 4.7,
    preparationTime: '10 min',
  },
  {
    id: '9',
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate caliente con helado de vainilla',
    price: 15000,
    image: '🍰',
    category: '5',
    rating: 4.9,
    preparationTime: '10-15 min',
  },
  {
    id: '10',
    name: 'Cheesecake',
    description: 'Cheesecake de frutos rojos',
    price: 18000,
    image: '🍰',
    category: '5',
    rating: 4.8,
    preparationTime: '10 min',
  },
  {
    id: '11',
    name: 'Pasta Carbonara',
    description: 'Pasta con salsa carbonara, tocino y parmesano',
    price: 28000,
    image: '🍝',
    category: '6',
    rating: 4.6,
    preparationTime: '25-30 min',
  },
  {
    id: '12',
    name: 'Pasta Bolognesa',
    description: 'Pasta con salsa bolognesa de carne',
    price: 26000,
    image: '🍝',
    category: '6',
    rating: 4.5,
    preparationTime: '25-30 min',
  },
  {
    id: '13',
    name: 'Pollo a la Parrilla',
    description: 'Pechuga de pollo a la parrilla con guarnición',
    price: 24000,
    image: '🍗',
    category: '7',
    rating: 4.4,
    preparationTime: '30-35 min',
  },
  {
    id: '14',
    name: 'Alitas Picantes',
    description: '10 alitas de pollo con salsa picante y aderezo ranch',
    price: 27000,
    image: '🍗',
    category: '7',
    rating: 4.7,
    preparationTime: '25-30 min',
  },
  {
    id: '15',
    name: 'Roll California',
    description: 'Rollo de sushi con cangrejo, aguacate y pepino',
    price: 32000,
    image: '🍣',
    category: '8',
    rating: 4.8,
    preparationTime: '20-25 min',
  },
  {
    id: '16',
    name: 'Roll Philadelphia',
    description: 'Rollo de sushi con salmón, queso crema y aguacate',
    price: 35000,
    image: '🍣',
    category: '8',
    rating: 4.9,
    preparationTime: '20-25 min',
  },
];